# Generated by Django 4.1.1 on 2022-09-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20, verbose_name='Название')),
                ('mod', models.CharField(max_length=20, verbose_name='Модель')),
                ('maxg', models.IntegerField(verbose_name='макс. груз')),
                ('ves', models.IntegerField(verbose_name='Текущий вес')),
                ('pere', models.IntegerField(verbose_name='перегруз,%')),
            ],
        ),
    ]
