# Generated by Django 4.1.1 on 2022-10-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiles',
            name='FE',
            field=models.IntegerField(default=0, verbose_name='FE,%'),
        ),
        migrations.AddField(
            model_name='artiles',
            name='SiO2',
            field=models.IntegerField(default=0, verbose_name='SiO2,%'),
        ),
    ]
