# Generated by Django 4.1.1 on 2022-10-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_artiles_fe_artiles_sio2'),
    ]

    operations = [
        migrations.AddField(
            model_name='artiles',
            name='koor',
            field=models.IntegerField(default=0, verbose_name='koor'),
        ),
    ]
