# Generated by Django 4.1.1 on 2022-11-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_artiles_koor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artiles',
            name='pere',
        ),
        migrations.AlterField(
            model_name='artiles',
            name='koor',
            field=models.IntegerField(default=0, verbose_name='Координата'),
        ),
    ]
